-- Migration to create cx_contact_messages table
create table cx_contact_messages (
  id bigint primary key generated by default as identity,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  company text not null,
  industry text,
  message text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable RLS
alter table cx_contact_messages enable row level security;

-- Add a comment for documentation
comment on table cx_contact_messages is 'Stores customer contact form submissions.';
