create table customer_request_for_quotes (
  id bigint primary key generated by default as identity,
  cx_rep_name text not null,
  cx_rep_title text,
  cx_company text not null,
  cx_rep_occupation text,
  cx_contact_number text,
  cx_address text,
  cx_email_addr text not null,
  cx_rfq_subject text not null,
  cx_rfq_msg text not null,
  quantity_needed int,
  expected_delivery_date date,
  cx_rfq_product text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
)